steps:
# Backend Build, Push, Deploy
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/erp-repo/backend:latest', './backend']
  id: 'Build Backend'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/erp-repo/backend:latest']
  id: 'Push Backend'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'school-erp-backend', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/erp-repo/backend:latest', '--region', 'us-central1']
  id: 'Deploy Backend'

# Frontend Build, Push, Deploy
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/erp-repo/frontend:latest', './frontend']
  id: 'Build Frontend'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/erp-repo/frontend:latest']
  id: 'Push Frontend'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'school-erp-frontend', '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/erp-repo/frontend:latest', '--region', 'us-central1']
  id: 'Deploy Frontend'

options:
  logging: CLOUD_LOGGING_ONLY

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/erp-repo/backend:latest'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/erp-repo/frontend:latest'
